### ISSUE TITLE
Group capstone: setting up Kanban board

### ISSUE THREAD

**Issue by danutibe07** [danutibe07/Javasript-Capstone-Project#21]
[Javascript Capstone project](https://github.com/danutibe07/Javasript-Capstone-Project/projects/1)

in my team, there are three Micronauts :
1.  danutibe07
2. Kaghenimbale
3. Rana-Mudassir

**Comment by julie-ify** [comment]
Hi @danutibe07, @Kaghenimbale,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should submit the Kanban project, not your repository

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by binhussen** [comment]
Hi @danutibe07 , @Rana-Mudassir and @Kaghenimbale 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- Prepared kanban board✔️
- Created all issues(Tasks) ✔️

## Required Changes ♻️
- Kindly, You should assign all tasks(issues) fairly to all group members, you can use the classification for group members based on `A`, `B`, and `C` tasks 
![2023-03-20_14-29](https://user-images.githubusercontent.com/52010789/226327914-437ea62e-0483-421a-a67d-9d1d8745d5ce.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @binhussen, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

Cheers and Happy coding!👏👏👏
